import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';

const data = [
    // {tir: 1, start: new Date("2018-03-29"), end: new Date("2020-04-03")},
    // {tir: 2, start: new Date("2020-05-27"), end: new Date("2020-06-03")},
    // {tir: 3, start: new Date("2020-01-26"), end: new Date("2020-03-03")},
    {tir: 1, start: new Date("2016-03-29"), end: new Date("2018-04-03")},
    {tir: 2, start: new Date("2017-05-27"), end: new Date("2018-06-03")},
    // {tir: 3, start: new Date("2020-01-26"), end: new Date("2020-03-03")},
    {tir: 2, start: new Date("2018-10-27"), end: new Date("2019-06-03")},
    // {tir: 4, start: new Date("2019-01-26"), end: new Date("2020-03-03")}
] 
console.log(data)

const exhibit_data = [{
      "id": "5",
      "owner_id": "2",
      "added": "2020-04-29 15:02:38",
      "modified": "2020-05-13 03:35:57",
      "published": "2020-05-12 03:46:57",
      "item_query": null,
      "spatial_layers": "OpenStreetMap,StamenToner,StamenWatercolor,StamenTerrain",
      "spatial_layer": "OpenStreetMap",
      "image_layer": null,
      "image_height": null,
      "image_width": null,
      "zoom_levels": "20",
      "wms_address": null,
      "wms_layers": null,
      "widgets": "Simile",
      "title": "Women HistoryMakers",
      "slug": "women-historymakers",
      "narrative": null,
      "spatial_querying": "1",
      "public": "1",
      "styles": ".all {\n  fill-opacity: 0.8;\n  fill-opacity-select: 1;\n  point-radius: 6;\n  stroke-width: 2;\n  stroke-color: white;\n  stroke-color-select: black;\n  stroke-opacity: 0.8;\n  stroke-opacity-select: 1;\n  map-focus: -10767225.550863,4172850.2475636;\n  map-zoom: 5;\n}\n\n.sportsmaker {\n  fill-color: #00aeff;\n  fill-color-select: #00aeff;\n}\n\n.musicmaker {\n  fill-color: #98df8a;\n  fill-color-select: #98df8a;\n}\n\n.educationmaker {\n  fill-color: #1f77b4;\n  fill-color-select: #1f77b4;\n}\n\n.civicmaker {\n  fill-color: #aec7e8;\n  fill-color-select: #aec7e8;\n}\n\n.mediamaker {\n  fill-color: #f0027f;\n  fill-color-select: #f0027f;\n}\n\n.artmaker {\n  fill-color: #f781bf;\n  fill-color-select: #f781bf;\n}\n\n.politicalmaker {\n  fill-color: #ff7f0e;\n  fill-color-select: #ff7f0e;\n}\n\n.lawmaker {\n  fill-color: #ffbb78;\n  fill-color-select: #ffbb78;\n}\n\n.businessmaker {\n  fill-color: #ffd92f;\n  fill-color-select: #ffd92f;\n}\n\n.entertainmentmaker {\n  fill-color: #2ca02c;\n  fill-color-select: #2ca02c;\n}",
      "map_focus": "-10767225.550863,4172850.2475636",
      "map_zoom": "5",
      "accessible_url": null,
      "map_restricted_extent": null,
      "map_min_zoom": "4",
      "map_max_zoom": "6"
  }]

const record_data = [
  {"tier":"1","id":"69","owner_id":"2","item_id":null,"exhibit_id":"5","added":"2020-04-29 15:06:48","modified":"2020-04-29 04:10:49","is_coverage":"1","is_wms":"0","slug":null,"title":"Lynn Carol Allen","item_title":null,"body":"<h4>EducationMaker, SportsMaker<br \/>Birthplace: Nashville, TN<\/h4>\n\n<h4 _ngcontent-c9=\"\">ABOUT LYNN CAROL ALLEN<\/h4>\n\n<p _ngcontent-c9=\"\">Education administrator and gymnastics coach Lynn Carol Allen (1951 - ) co-founded Tri-Star Gymnastics outside of Chicago in the town of Forest Park. Tri-Star serves the gymnastics community of the near western suburbs and the City of Chicago.<\/p>\n\n<p _ngcontent-c9=\"\"><a _ngcontent-c9=\"\" href=\"https:\/\/virginia-thehistorymakers-org.proxy01.its.virginia.edu\/storiesForBio;ID=A2005.222\" routerlinkactive=\"active\">To see the entire interview, click here<\/a>.<\/p>\n","coverage":"0x00000000010700000001000000010100000016bd53bcb36c62c1f26327f5287c5041","tags":"sportsmaker","widgets":"Simile","presenter":"StaticBubble","fill_color":"#00aeff","fill_color_select":"#00aeff","stroke_color":"white","stroke_color_select":"black","fill_opacity":"0.80","fill_opacity_select":"1.00","stroke_opacity":"0.80","stroke_opacity_select":"1.00","stroke_width":"2","point_radius":"6","zindex":null,"weight":null,"start_date":"1951-10-22","end_date":"1954-10-22","after_date":null,"before_date":null,"point_image":null,"wms_address":null,"wms_layers":null,"min_zoom":null,"max_zoom":null,"map_zoom":"5","map_focus":"-10767225.550863,4172850.2475636"},
  {"tier":"1","id":"60","owner_id":"2","item_id":null,"exhibit_id":"5","added":"2020-04-29 15:26:15","modified":"2020-04-29 04:10:36","is_coverage":"1","is_wms":"0","slug":null,"title":"Katherine Bennett","item_title":null,"body":"<h4>EducationMaker, SportsMaker<\/h4>\n\n<h4>Birthplace: Elizabeth City, NC, USA<\/h4>\n\n<h4 _ngcontent-c9=\"\">ABOUT KATHERINE BENNETT<\/h4>\n\n<p _ngcontent-c9=\"\">Academic administrator and college basketball coach Katherine Bennett (1922 - 2009 ) was a pioneer in women&rsquo;s athletics, coaching the first competitive women&rsquo;s basketball game, integrating women&rsquo;s athletics into the CIAA and becoming the first female chair of the department. She was recognized by the Virginia Sports Hall of Fame for her accomplishments in women&#39;s sports.<\/p>\n\n<p _ngcontent-c9=\"\"><a _ngcontent-c9=\"\" href=\"https:\/\/virginia-thehistorymakers-org.proxy01.its.virginia.edu\/storiesForBio;ID=A2004.200\" routerlinkactive=\"active\">To see the entire interview, click here<\/a>.<\/p>\n","coverage":"0x000000000107000000010000000101000000a3a366e0e62e60c188380ccb33905041","tags":"sportsmaker","widgets":"Simile","presenter":"StaticBubble","fill_color":"#98df8a","fill_color_select":"#00aeff","stroke_color":"white","stroke_color_select":"black","fill_opacity":"0.80","fill_opacity_select":"1.00","stroke_opacity":"0.80","stroke_opacity_select":"1.00","stroke_width":"2","point_radius":"6","zindex":null,"weight":null,"start_date":"1932-10-17","end_date":"1933-10-17","after_date":null,"before_date":null,"point_image":null,"wms_address":null,"wms_layers":null,"min_zoom":null,"max_zoom":null,"map_zoom":"5","map_focus":"-10767225.550863,4172850.2475636"},
  {"tier":null,"id":"61","owner_id":"2","item_id":null,"exhibit_id":"5","added":"2020-04-29 15:31:03","modified":"2020-04-29 04:10:24","is_coverage":"1","is_wms":"0","slug":null,"title":"Evie Garrett Dennis","item_title":null,"body":"<h4>EducationMaker, SportsMaker<\/h4>\n\n<h4>Birthplace: Farmhaven, MS<\/h4>\n\n<h4 _ngcontent-c9=\"\">ABOUT EVIE GARRETT DENNIS<\/h4>\n\n<p _ngcontent-c9=\"\">City education administrator and olympics executive Evie Garrett Dennis (1924 - ) was the first woman and first person of color to serve as the vice president of the U.S. Olympic Committee. She was also the first woman and first African American superintendent of the Denver Public Schools, where she was instrumental in the desegregation process.<\/p>\n\n<p _ngcontent-c9=\"\"><a _ngcontent-c9=\"\" href=\"https:\/\/virginia-thehistorymakers-org.proxy01.its.virginia.edu\/storiesForBio;ID=A2008.118\" routerlinkactive=\"active\">To see the entire interview, click here<\/a>.<\/p>\n","coverage":"0x00000000010700000001000000010100000070057991b01163c113fa4f5ad55c4d41","tags":"sportsmaker","widgets":"Simile","presenter":"StaticBubble","fill_color":"#00aeff","fill_color_select":"#00aeff","stroke_color":"white","stroke_color_select":"black","fill_opacity":"0.80","fill_opacity_select":"1.00","stroke_opacity":"0.80","stroke_opacity_select":"1.00","stroke_width":"2","point_radius":"6","zindex":null,"weight":null,"start_date":"1944-9-8","end_date":"1945-9-8","after_date":null,"before_date":null,"point_image":null,"wms_address":null,"wms_layers":null,"min_zoom":null,"max_zoom":null,"map_zoom":"5","map_focus":"-10767225.550863,4172850.2475636"},
  {"tier":null,"id":"62","owner_id":"2","item_id":null,"exhibit_id":"5","added":"2020-04-29 15:37:26","modified":"2020-04-29 04:10:04","is_coverage":"1","is_wms":"0","slug":null,"title":"Benita Fitzgerald Mosley","item_title":null,"body":"<h4>CivicMaker, SportsMaker<\/h4>\n\n<h4>Birthplace: Dale City, VA<\/h4>\n\n<h2 _ngcontent-c7=\"\">BIOGRAPHY<\/h2>\n\n<p _ngcontent-c7=\"\">Track and field athlete and nonprofit executive Benita Fitzgerald Mosley was born on July 6, 1961 in Dale City, Virginia. She graduated from the University of Tennessee in 1984 with her degree in industrial engineering. That year, she won a gold medal in the 100-meter hurdles in the Olympic Games. She was the second American and the only African American woman to win an Olympic gold medal in the 100-meter hurdles. After working as an engineer, Mosley turned to sports marketing and administration. In 1995, she joined the United States Olympic Committee. From 1997 until 2000, she served as USOC&#39;s director of Olympic training centers. In 2001, Mosley was appointed president of Women in Cable and Telecommunications. She received several awards for her athletic and professional work, and in 1996, Mosely was one of eight U.S. Olympians chosen to carry the Olympic flag into the stadium during the Atlanta Olympics.<\/p>\n\n<p _ngcontent-c9=\"\"><a _ngcontent-c9=\"\" href=\"https:\/\/virginia-thehistorymakers-org.proxy01.its.virginia.edu\/storiesForBio;ID=A2003.012\" routerlinkactive=\"active\">To see the entire interview, click here<\/a>.<\/p>\n","coverage":"0x0000000001070000000100000001010000008399c0e49b6a60c1541f48280cd15141","tags":"sportsmaker","widgets":"Simile","presenter":"StaticBubble","fill_color":"#00aeff","fill_color_select":"#00aeff","stroke_color":"white","stroke_color_select":"black","fill_opacity":"0.80","fill_opacity_select":"1.00","stroke_opacity":"0.80","stroke_opacity_select":"1.00","stroke_width":"2","point_radius":"6","zindex":null,"weight":null,"start_date":"1961-7-6","end_date":null,"after_date":null,"before_date":null,"point_image":null,"wms_address":null,"wms_layers":null,"min_zoom":null,"max_zoom":null,"map_zoom":"5","map_focus":"-10767225.550863,4172850.2475636"},
  {"tier":null,"id":"63","owner_id":"2","item_id":null,"exhibit_id":"5","added":"2020-04-29 16:02:32","modified":"2020-04-29 04:09:45","is_coverage":"1","is_wms":"0","slug":null,"title":"Dionne Warwick","item_title":null,"body":"<h3>MusicMaker<\/h3>\n\n<h3>Birthplace: East Orange, NJ<\/h3>\n\n<h2 _ngcontent-c7=\"\">BIOGRAPHY<\/h2>\n\n<p _ngcontent-c7=\"\">Singer Dionne Warwick was born in East Orange, New Jersey, on December 12, 1940. The oldest of three siblings, Warwick was raised in a deeply religious and musical family. At fourteen, Warwick helped form The Gospelaires. In 1959, Warwick received a music scholarship to the University of Hartford. Warwick signed a recording contract in 1962 and her first single, Don&#39;t Make Me Over, was a hit, attracting both R&amp;B and pop audiences. From 1963 to 1966, Warwick achieved unprecedented success by becoming the first crossover artist to have a dozen consecutive Top 100 hits. Known for her partnership with songwriters,&nbsp;Burt Bacharach&nbsp;and&nbsp;Hal David, she became the first African American solo female artist to receive a Grammy for Do You Know the Way to San Jose in 1968. By 1970, she had recorded thirty hit singles, close to twenty best-selling albums and received a second Grammy for the album, I&#39;ll Never Fall In Love Again.<\/p>\n\n<p _ngcontent-c7=\"\"><a _ngcontent-c9=\"\" href=\"https:\/\/virginia-thehistorymakers-org.proxy01.its.virginia.edu\/storiesForBio;ID=A2001.087\" routerlinkactive=\"active\">To see the entire interview, click here<\/a>.<\/p>\n","coverage":"0x0000000001070000000100000001010000005ae553a2ec825fc1f5eb18b7acfc5241","tags":"musicmaker","widgets":"Simile","presenter":"StaticBubble","fill_color":"#98df8a","fill_color_select":"#98df8a","stroke_color":"white","stroke_color_select":"black","fill_opacity":"0.80","fill_opacity_select":"1.00","stroke_opacity":"0.80","stroke_opacity_select":"1.00","stroke_width":"2","point_radius":"6","zindex":null,"weight":null,"start_date":null,"end_date":null,"after_date":null,"before_date":null,"point_image":null,"wms_address":null,"wms_layers":null,"min_zoom":null,"max_zoom":null,"map_zoom":"5","map_focus":"-10767225.550863,4172850.2475636"},
  {"tier":"2","id":"64","owner_id":"2","item_id":null,"exhibit_id":"5","added":"2020-04-29 16:20:40","modified":"2020-04-29 04:56:55","is_coverage":"1","is_wms":"0","slug":null,"title":"Billie Allen","item_title":null,"body":"<h3>ArtMaker<br \/>Birthplace: Richmond, VA<\/h3>\n\n<p><a _ngcontent-c9=\"\" href=\"https:\/\/virginia-thehistorymakers-org.proxy01.its.virginia.edu\/storiesForBio;ID=A2007.142\" routerlinkactive=\"active\">To see the entire interview, click here<\/a>.<\/p>\n\n<h2 _ngcontent-c7=\"\">BIOGRAPHY<\/h2>\n\n<p _ngcontent-c7=\"\">Actress and stage director Billie Allen was born Wilhelmina Louise Allen on January 13, 1925 in Richmond, Virginia. Briefly attending Hampton University, Allen moved to New York City in 1943 to study acting at the Lee Strasburg Institute. In 1953, she appeared on Broadway in Take A Giant Step with Lou Gossett and Godfrey Cambridge. She portrayed Vertel in the movie Black Like Me and appeared on stage in James Baldwin&rsquo;s Blues for Mister Charlie. Allen was also featured in Route 66, Car 54, Where Are You?, The Wiz, The Nurses, Winter Kills, The Vernon Johns Story, Eddie Murphy Raw, and Losing Ground. Allen directed Danny Glover in the play Home, and Ruby Dee in the play Saint Lucy&#39;s Eyes in New York. She served on the Tony Awards Committee and co-founded the Frank Silvera Writers Workshop. Allen passed away on December 29, 2015 at the age of ninety.<\/p>\n","coverage":"0x000000000107000000010000000101000000acdc70718f7160c144db31d9f7375141","tags":"artmaker","widgets":"Simile","presenter":"StaticBubble","fill_color":"#f781bf","fill_color_select":"#f781bf","stroke_color":"white","stroke_color_select":"black","fill_opacity":"0.80","fill_opacity_select":"1.00","stroke_opacity":"0.80","stroke_opacity_select":"1.00","stroke_width":"2","point_radius":"6","zindex":null,"weight":null,"start_date":"1925-1-13","end_date":null,"after_date":null,"before_date":null,"point_image":null,"wms_address":null,"wms_layers":null,"min_zoom":null,"max_zoom":null,"map_zoom":"5","map_focus":"-10767225.550863,4172850.2475636"},
  {"tier":null,"id":"65","owner_id":"2","item_id":null,"exhibit_id":"5","added":"2020-04-29 17:00:08","modified":"2020-04-29 05:01:11","is_coverage":"1","is_wms":"0","slug":null,"title":"Madeleine Moore Burrell","item_title":null,"body":"<h3>MediaMaker<br \/>Birthplace:&nbsp;Brooklyn, NY<\/h3>\n\n<p><a _ngcontent-c9=\"\" href=\"https:\/\/virginia-thehistorymakers-org.proxy01.its.virginia.edu\/storiesForBio;ID=A2014.120\" routerlinkactive=\"active\">To see the entire interview, click here<\/a>.<\/p>\n\n<h2 _ngcontent-c7=\"\">BIOGRAPHY<\/h2>\n\n<p _ngcontent-c7=\"\">Marketing executive Madeleine Moore Burrell was born in 1940. She received her B.F.A. degree from New York University, and her M.F.A. degree in writing from Columbia University. She also studied industrial design at the Parsons School of Design. Moore Burrell first worked as an industrial designer with Henry Dreyfuss Associates and Goretz Industrial Design. She designed many products, including the first plastic hangers in the United States. In 1985, Moore Burrell founded Moore Creative, a New York marketing firm. Moore Creative was the first African American marketing firm awarded a post-apartheid contract with South Africa, launching the Sister City agreement between New York City and Johannesburg. She was a founder of the 21st Century Women&#39;s Leadership Center, and co-founder of the National Professionals Network, Inc. She served as president of the New York Coalition of 100 Black Women and AARP of New York State, as well as chairman of Public New York.<\/p>\n","coverage":"0x000000000107000000010000000101000000be2951ddc0675fc1b284b5c953ec5241","tags":"mediamaker","widgets":"Simile","presenter":"StaticBubble","fill_color":"#f0027f","fill_color_select":"#f0027f","stroke_color":"white","stroke_color_select":"black","fill_opacity":"0.80","fill_opacity_select":"1.00","stroke_opacity":"0.80","stroke_opacity_select":"1.00","stroke_width":"2","point_radius":"6","zindex":null,"weight":null,"start_date":"1940-9-10","end_date":null,"after_date":null,"before_date":null,"point_image":null,"wms_address":null,"wms_layers":null,"min_zoom":null,"max_zoom":null,"map_zoom":"5","map_focus":"-10767225.550863,4172850.2475636"},
  {"tier":"2","id":"66","owner_id":"2","item_id":null,"exhibit_id":"5","added":"2020-04-29 17:22:08","modified":"2020-04-29 05:23:23","is_coverage":"1","is_wms":"0","slug":null,"title":"Anna Langford","item_title":null,"body":"<h3>LawMaker, PoliticalMaker <br \/>Birthplace:&nbsp;Springfield, OH<\/h3>\n\n<p><a _ngcontent-c9=\"\" href=\"https:\/\/virginia-thehistorymakers-org.proxy01.its.virginia.edu\/storiesForBio;ID=A2002.190\" routerlinkactive=\"active\">To see the entire interview, click here<\/a>.<\/p>\n\n<h2 _ngcontent-c7=\"\">BIOGRAPHY<\/h2>\n\n<p _ngcontent-c7=\"\">Civil rights lawyer and city government official Anna Langford was born on October 27, 1917 in Springfield, Ohio. After graduation from Hyde Park High School in Chicago in 1935, she attended a trade school. From 1938 to 1956, she worked as a typist in the Social Security office, the Election Commissioners Office and the Office of the Secretary of State. In 1956, she received her J.D. degree from Roosevelt University and began a career as civil rights and criminal lawyer. Langford practiced throughout Illinois, actively defending civil rights workers in the 1960s. She joined Reverend Dr. Martin Luther King, Jr.&rsquo;s Chicago civil rights marches. In 1971, Langford became one of the first two women elected to the Chicago City Council. She returned later to serve two additional terms from 1983 until 1991. She received numerous humanitarian and civic awards and honors. Langford passed away on September 17, 2008 at age 90.<\/p>\n","coverage":"0x00000000010700000001000000010100000013765b65eacb61c1c3c8dc7c1a845241","tags":"lawmaker","widgets":"Simile","presenter":"StaticBubble","fill_color":"#ffbb78","fill_color_select":"#ffbb78","stroke_color":"white","stroke_color_select":"black","fill_opacity":"0.80","fill_opacity_select":"1.00","stroke_opacity":"0.80","stroke_opacity_select":"1.00","stroke_width":"2","point_radius":"6","zindex":null,"weight":null,"start_date":"1917-10-27","end_date":null,"after_date":null,"before_date":null,"point_image":null,"wms_address":null,"wms_layers":null,"min_zoom":null,"max_zoom":null,"map_zoom":"5","map_focus":"-10767225.550863,4172850.2475636"},
  {"tier":null,"id":"67","owner_id":"2","item_id":null,"exhibit_id":"5","added":"2020-04-30 17:55:38","modified":"2020-04-30 05:57:04","is_coverage":"1","is_wms":"0","slug":null,"title":"Ruth Beckford","item_title":null,"body":"<h3>ArtMaker<br \/>Birthplace: Oakland, CA<\/h3>\n\n<p><a _ngcontent-c7=\"\" href=\"https:\/\/virginia-thehistorymakers-org.proxy01.its.virginia.edu\/storiesForBio;ID=A2002.031\" routerlinkactive=\"active\">To see the entire interview, click here<\/a>.<\/p>\n\n<h2 _ngcontent-c2=\"\">BIOGRAPHY<\/h2>\n\n<p _ngcontent-c2=\"\">Choreographer and dancer Ruth Beckford was born on December 7, 1925 in Oakland, California. She began dancing at age three. In 1943, Beckford toured with the legendary Katherine Dunham; and, in 1947, she founded the first recreational modern dance department in the United States at the Oakland Department of Parks and Recreation. Beckford opened the Ruth Beckford African-Haitian Dance Company in 1953. She closed her dance studio in 1975, but continued to perform. She co-wrote, produced, and starred in &#39;Tis the Morning of My Life, an off-Broadway success. Beckford also played major television and film roles, appearing in Angels in the Outfield, The Principal, and Midnight Caller. She counseled homeless people at the Berkeley office of the Department of Social Services between 1990 and 1997, then became a life skills counselor at the Oakland Private Industry Council. Beckford wrote several books, including Still Groovin&#39;: Affirmations for Women in the Second Half of Life.<\/p>\n","coverage":"0x000000000107000000010000000101000000bce7c093a9f669c10b4c02ce835d5141","tags":"artmaker","widgets":"Simile","presenter":"StaticBubble","fill_color":"#f781bf","fill_color_select":"#f781bf","stroke_color":"white","stroke_color_select":"black","fill_opacity":"0.80","fill_opacity_select":"1.00","stroke_opacity":"0.80","stroke_opacity_select":"1.00","stroke_width":"2","point_radius":"6","zindex":null,"weight":null,"start_date":"1925-12-7","end_date":null,"after_date":null,"before_date":null,"point_image":null,"wms_address":null,"wms_layers":null,"min_zoom":null,"max_zoom":null,"map_zoom":"5","map_focus":"-10767225.550863,4172850.2475636"},
  ]

ReactDOM.render(
  <React.StrictMode>
    <App data={record_data}/>
  </React.StrictMode>,
  document.getElementById('root')
);

